export const ADMIN_FETCH_USERS_SUCCESS = "ADMIN_FETCH_USERS_SUCCESS";
export const ADMIN_FETCH_USERS_FAILURE = "ADMIN_FETCH_USERS_FAILURE";

export const ADMIN_FETCH_POSTS_SUCCESS = "ADMIN_FETCH_POSTS_SUCCESS";
export const ADMIN_FETCH_POSTS_FAILURE = "ADMIN_FETCH_POSTS_FAILURE";

export const ADMIN_BANUNBAN_SUCCESS = "ADMIN_BANUNBAN_SUCCESS";
export const ADMIN_BANUNBAN_FAILURE = "ADMIN_BANUNBAN_FAILURE";

export const ADMIN_PROMOTE_USER_SUCCESS = "ADMIN_PROMOTE_USER_SUCCESS";
export const ADMIN_PROMOTE_USER_FAILURE = "ADMIN_PROMOTE_USER_FAILURE";

export const ADMIN_STATE_RESET = "ADMIN_STATE_RESET";
