export const POSTS_ERROR = "POSTS_ERROR";
export const CLEAR_POST_RESET = "CLEAR_POST_RESET";
export const LATEST_POSTS_DATA = "LATEST_POSTS_DATA";
export const ALL_POSTS_DATA = "ALL_POSTS_DATA";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";
export const POST_CREATE_RESET = "POST_CREATE_RESET";
export const POST_DETAIL_FETCH = "POST_DETAIL_FETCH";
export const POST_DETAIL_SUCCESS = "POST_DETAIL_SUCCESS";
export const POST_DETAIL_FAILURE = "POST_DETAIL_FAILURE";
export const POST_DETAIL_RESET = "POST_DETAIL_RESET";

export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_FAILURE = "FETCH_BOOKMARK_ERROR";
export const FETCH_BOOKMARK_RESET = "FETCH_BOOKMARK_RESET";

export const POST_SUBMIT_RATING_SUCCESS = "POST_SUBMIT_RATING_SUCCESS";
export const POST_SUBMIT_RATING_FAILURE = "POST_SUBMIT_RATING_FAILURE";

export const POST_REPORT_BLOG_SUCCESS = "POST_REPORT_BLOG_SUCCESS";
export const POST_REPORT_BLOG_FAILURE = "POST_SUBMIT_RATING_FAILURE";
