export const POSTS_ERROR = "POSTS_ERROR";
export const CLEAR_POST_RESET = "CLEAR_POST_RESET";
export const LATEST_POSTS_DATA = "LATEST_POSTS_DATA";
export const ALL_POSTS_DATA = "ALL_POSTS_DATA";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";
export const POST_CREATE_RESET = "POST_CREATE_RESET";
