export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAILURE = "PROFILE_FETCH_FAILURE";
export const PROFILE_FETCH_RESET = "PROFILE_FETCH_RESET";
export const PROFILE_PASSWORD_SUCCESS = "PROFILE_PASSWORD_SUCCESS";
export const PROFILE_PASSWORD_FAILURE = "PROFILE_PASSWORD_FAILURE";
export const PROFILE_UPDATE_SOCIALS_SUCCESS = "PROFILE_UPDATE_SOCIALS_SUCCESS";
export const PROFILE_UPDATE_SOCIALS_FAILURE = "PROFILE_UPDATE_SOCIALS_FAILURE";
